/*
 * ws2812_led.h
 *
 *  Created on: Jul 18, 2024
 *      Author: hp
 */

#ifndef INC_WS2812_LED_H_
#define INC_WS2812_LED_H_

#include "stm32u5xx_hal.h" // Include the HAL library header

// Function Declarations for WS2812 LED control

// Set LED Colors (Assuming RGB LEDs)
#define WS2812_SET_LED_RED_HIGH()    HAL_GPIO_WritePin(DIODE_LED_GPIO_RED_PIN_GPIO_Port, DIODE_LED_GPIO_RED_PIN_Pin, GPIO_PIN_SET)
#define WS2812_SET_LED_GREEN_HIGH()  HAL_GPIO_WritePin(DIODE_LED_GPIO_GREEN_PIN_GPIO_Port, DIODE_LED_GPIO_GREEN_PIN_Pin, GPIO_PIN_SET)
#define WS2812_SET_LED_BLUE_HIGH()   HAL_GPIO_WritePin(DIODE_LED_GPIO_BLUE_PIN_GPIO_Port, DIODE_LED_GPIO_BLUE_PIN_Pin, GPIO_PIN_SET)

#define WS2812_SET_LED_RED_LOW()     HAL_GPIO_WritePin(DIODE_LED_GPIO_RED_PIN_GPIO_Port, DIODE_LED_GPIO_RED_PIN_Pin, GPIO_PIN_RESET)
#define WS2812_SET_LED_GREEN_LOW()   HAL_GPIO_WritePin(DIODE_LED_GPIO_GREEN_PIN_GPIO_Port, DIODE_LED_GPIO_GREEN_PIN_Pin, GPIO_PIN_RESET)
#define WS2812_SET_LED_BLUE_LOW()    HAL_GPIO_WritePin(DIODE_LED_GPIO_BLUE_PIN_GPIO_Port, DIODE_LED_GPIO_BLUE_PIN_Pin, GPIO_PIN_RESET)

#endif /* INC_WS2812_LED_H_ */
