/*
 * ws2812_led.h
 *
 *  Created on: Jul 18, 2024
 *      Author: hp
 */

#ifndef INC_WS2812_LED_H_
#define INC_WS2812_LED_H_
//LED RGB 5mm Dip 4
// Function Declarations

#define DIODE_STM32_SET_LED_RED_High()    HAL_GPIO_WritePin(DIODE_LED_GPIO_RED_PIN_GPIO_Port,DIODE_LED_GPIO_RED_PIN_Pin, GPIO_PIN_SET)
#define DIODE_STM32_SET_LED_GREEN_High()  HAL_GPIO_WritePin(DIODE_LED_GPIO_GREEN_PIN_GPIO_Port, DIODE_LED_GPIO_GREEN_PIN_Pin, GPIO_PIN_SET)
#define DIODE_STM32_SET_LED_BLUE_High() HAL_GPIO_WritePin(DIODE_LED_GPIO_YELLOW_PIN_GPIO_Port, DIODE_LED_GPIO_YELLOW_PIN_Pin, GPIO_PIN_SET)
#define DIODE_STM32_SET_LED_GREEN_LOW()   HAL_GPIO_WritePin(DIODE_LED_GPIO_RED_PIN_GPIO_Port,DIODE_LED_GPIO_RED_PIN_Pin, GPIO_PIN_RESET)
#define DIODE_STM32_SET_LED_RED_LOW()     HAL_GPIO_WritePin(DIODE_LED_GPIO_GREEN_PIN_GPIO_Port, DIODE_LED_GPIO_GREEN_PIN_Pin, GPIO_PIN_RESET)
#define DIODE_STM32_SET_LED_BLUE_LOW()  HAL_GPIO_WritePin(DIODE_LED_GPIO_YELLOW_PIN_GPIO_Port, DIODE_LED_GPIO_YELLOW_PIN_Pin, GPIO_PIN_RESET)

#endif /* INC_WS2812_LED_H_ */
